apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flogis-blog

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - resource-policy.yaml
  - web.yaml
  - tailscale-gateway.yaml

configMapGenerator:
  - name: flogis-blog-gateway
    files:
      - default.conf=files/gateway.conf
  - name: flogis-blog-runtime
    literals:
      - TS_KUBE_SECRET=flogis-blog-tailscale-state
      - TS_HOSTNAME=flogis-blog
      - TS_ADVERTISE_TAGS=tag:flogis-blog

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: flogis-blog
    includeSelectors: false
