apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flogis-blog

resources:
  - ../../base

images:
  - name: harbor.192.168.0.110.nip.io/flogy_blog/site
    newTag: replace-with-jenkins-build

replicas:
  - name: flogis-blog-web
    count: 2
  - name: flogis-blog-gateway
    count: 1
